GET http://localhost:5109/vacancies

###
GET http://localhost:5109/vacancies/search?query=Дегустатор
###
GET http://localhost:5109/vacancies/2

###
POST http://localhost:5109/vacancies
Content-Type: application/json

{
    "firmName" : "Light Side",
    "ProfessionId" : 2,
    "requirements" : "Мати власту лопату"
}

###
PUT http://localhost:5109/vacancies/2
Content-Type: application/json

{
    "id": 2,
    "firmName": "Light Side",
    "ProfessionId": 3,
    "workingCondition": null,
    "payment": 0,
    "livingCondition": null,
    "requirements": "Мати власту лопату"
}

###
DELETE http://localhost:5109/vacancies/2
